# 前端构建
FROM quay.io/0voice/node:18.16.0 as stage0
RUN npm config set registry https://mirrors.huaweicloud.com/repository/npm/
COPY ./ai-transform-web /src/ai-transform-web
WORKDIR /src/ai-transform-web
RUN npm install
RUN npm run build

# 后端构建
FROM quay.io/0voice/golang:1.24 as stage1
RUN go env -w GOPROXY=https://goproxy.cn,https://proxy.golang.com.cn,direct
ADD ./ai-transform-backend /src/ai-transform-backend
WORKDIR /src/ai-transform-backend
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ai-transform-web-api ./transform-web-api

FROM quay.io/0voice/alpine:3.18 as stage2
MAINTAINER nick
WORKDIR /app/
ADD ./ai-transform-backend/dev.config.yaml /app/config.yaml
COPY --from=stage0 /src/ai-transform-web/dist /app/www
COPY --from=stage1 /src/ai-transform-backend/ai-transform-web-api /app
# 指定入口程序
ENTRYPOINT ["./ai-transform-web-api"]
# 指定容器的启动命令或者入口程序的参数
CMD ["--config=config.yaml"]